adv_varnish.cache_settings:
  type: config_object
  label: 'Advanced varnish module settings'
  mapping:
    general:
      type: mapping
      mapping:
        page_cache_maximum_age:
          type: string
          label: 'Page cache TTL'
        noise:
          type: string
          label: 'This works as private key'
        debug:
          type: string
          label: 'Debug mode'
        logging:
          type: string
          label: 'Logging'
        secret:
          type: string
          label: 'Varnish secret'
        varnish_server:
          type: string
          label: 'Varnish server host'
        varnish_purger:
          type: boolean
          label: 'Enable Varnish built-in purger'
        purger_maintenance_mode:
          type: boolean
          label: 'Prevent Varnish purge while in Maintenance Mode'
    available:
      type: mapping
      mapping:
        enable_cache:
          type: boolean
          label: 'Enable Varnish cache'
        authenticated_users:
          type: boolean
          label: 'Enable varnish for authenticated users'
        esi:
          type: boolean
          label: 'Enable Varnish ESI support'
        esi_purge_user_blocks:
          type: boolean
          label: 'If this is checked "user:id" tag will be purged on POST request'
        excluded_urls:
          type: string
          label: 'Enable Varnish ESI support'
    cache_control:
      type: mapping
      mapping:
        anonymous:
          type: string
          label: 'Cache control headers for anonymous users'
        authenticated:
          type: string
          label: 'Cache control headers for logged in users'
