<?php
    use Drupal\Core\Form\FormStateInterface;
    use Drupal\node\Entity\Node;
    use Drupal\taxonomy\Entity\Term;
    use Drupal\Core\Entity\EntityInterface;

function niit_community_gallery_theme($existing, $type, $theme, $path){
    return array('my-customfunctions' =>
        array(
            'variables' => array(
                'arguments' => NULL
            ),

        )
    );
}
function niit_community_gallery_entity_update(EntityInterface $entity) {	
        
        $timestamp = $entity->changed = time();
		if($entity->bundle() == 'course'){
			 $appid = $entity->id();
	
 //$url = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/niit_course_details&api_id=$appid";
 $urlone = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/advanced_track&api_id=$appid";
	   $data_array = array(
			"timestamp"=> $timestamp,
			"api_id"=> $appid,
			
			);
			
			$data_json = json_encode($data_array);
       //$data = json_encode($data);
        $headers = array(
            "timestamp: 1000",
			"Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2OTIiLCJpc3QiOjE2NDA5NTE1NTk1NzV9.D9vt5c78eBhKlyrZl_LWdQ9-niceyGI-qYsg3OshFNM",
			"Content-Type: application/json",
        );
        $ch = curl_init();
          //curl_setopt($ch, CURLOPT_URL, $url);
		  curl_setopt($ch, CURLOPT_URL, $urlone);
          curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
          curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json );
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
          $response = curl_exec($ch);
		 // $data_response = json_decode($response);
          curl_close($ch);
     // echo '<pre>'; print_r($response); print_r($data_json); die();
	 drupal_set_message(t('Node is successfully update')); 
  // drupal_set_message(print_r($entity->bundle() == 'course', true));
   //drupal_set_message(print_r($entity->changed = time(), true));
   //drupal_set_message(print_r($entity->get('field_course_')->target_id, true));
  // drupal_set_message(print_r($url, true));
  // drupal_set_message(print_r($entity->id(), true));
         return $response;
		 }
 }
  function niit_community_gallery_entity_delete(EntityInterface $entity) {
	  $timestamp = $entity->changed = time();
		if($entity->bundle() == 'course'){
			 $appid = $entity->id();
	
 //$url = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/niit_course_details&api_id=$appid";
 $urlone = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/advanced_track&api_id=$appid";
	   $data_array = array(
			"timestamp"=> $timestamp,
			"api_id"=> $appid,
			
			);
			
			$data_json = json_encode($data_array);
       //$data = json_encode($data);
        $headers = array(
            "timestamp: 1000",
			"Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2OTIiLCJpc3QiOjE2NDA5NTE1NTk1NzV9.D9vt5c78eBhKlyrZl_LWdQ9-niceyGI-qYsg3OshFNM",
			"Content-Type: application/json",
        );
        $ch = curl_init();
         // curl_setopt($ch, CURLOPT_URL, $url);
		  curl_setopt($ch, CURLOPT_URL, $urlone);
          curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
          curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json );
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
          $response = curl_exec($ch);
		 // $data_response = json_decode($response);
          curl_close($ch);
     // echo '<pre>'; print_r($response); print_r($data_json); die();
	 drupal_set_message(t('Node is successfully delete')); 
  // drupal_set_message(print_r($entity->bundle() == 'course', true));
   //drupal_set_message(print_r($entity->changed = time(), true));
   //drupal_set_message(print_r($entity->get('field_course_')->target_id, true));
  // drupal_set_message(print_r($url, true));
  // drupal_set_message(print_r($entity->id(), true));
         return $response;
		 }
	  
  }
  function niit_community_gallery_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {	
        
        $timestamp = $entity->changed = time();
		if($entity->bundle() == 'course'){
			 $appid = $entity->id();
	
 //$url = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/niit_course_details&api_id=$appid";
 $urlone = "https://learner-engagementsystem-stg.training.com/learnerengagementsystem/api/update/Timestamp?deviceid=Annonymous&apiname=/advanced_track&api_id=$appid";
	   $data_array = array(
			"timestamp"=> $timestamp,
			"api_id"=> $appid,
			
			);
			
			$data_json = json_encode($data_array);
       //$data = json_encode($data);
        $headers = array(
            "timestamp: 1000",
			"Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2OTIiLCJpc3QiOjE2NDA5NTE1NTk1NzV9.D9vt5c78eBhKlyrZl_LWdQ9-niceyGI-qYsg3OshFNM",
			"Content-Type: application/json",
        );
        $ch = curl_init();
          //curl_setopt($ch, CURLOPT_URL, $url);
		  curl_setopt($ch, CURLOPT_URL, $urlone);
          curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
          curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json );
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
          $response = curl_exec($ch);
		 // $data_response = json_decode($response);
          curl_close($ch);
     // echo '<pre>'; print_r($response); print_r($data_json); die();
	 drupal_set_message(t('Node is successfully created')); 
  // drupal_set_message(print_r($entity->bundle() == 'course', true));
   //drupal_set_message(print_r($entity->changed = time(), true));
   //drupal_set_message(print_r($entity->get('field_course_')->target_id, true));
  // drupal_set_message(print_r($url, true));
  // drupal_set_message(print_r($entity->id(), true));
         return $response;
		 }
 }
