<?php

use Drupal\node\Entity\Node; 
use Drupal\user\Entity\User;
use Drupal\Core\Form\FormStateInterface;


function ms_ajax_form_example_page_attachments(array &$attachments) {
    // Unconditionally attach an asset to the page.
    $attachments['#attached']['library'][] = 'ms_ajax_form_example/ms_ajax_form_example.library';   
}


function ms_ajax_form_example_preprocess_page(&$variables) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
      $node = \Drupal\node\Entity\Node::load($node->id());
      $freeTrialTitle = $node->field_free_trial_cta_title->value;
      //$config = \Drupal::config('ms_ajax_form_example.settings'); 
      $variables['mutlistep_apply_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Apply Now</span>';

      $variables['mutlistep_request_call_btn'] = '<button class="btn btnReqCall" onclick="popupicici_popup()"><i class="fa fa-phone"></i> Request a call back</button>';

      $variables['mutlistep_check_eligibility_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Check Eligibility</span>';

      $variables['mutlistep_connectus_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Connect with us</span>';
      $variables['free_trial_apply_btn'] = '<span class="btn btn-primary btnApply free-trialCTA" onclick="popupicicifree_popup()">'.$freeTrialTitle.' <i class="fa fa-chevron-right"></i></span>';
  }

  /*$node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $node = \Drupal\node\Entity\Node::load($node->id());
    $nid = $node->id();
    $ContentTypeName = $node->bundle();
    $template_type = '';
    if($ContentTypeName == 'course'){
      $template_type = $node->field_select_template->value; 
      if($template_type == 'course_new_stack_route' || $template_type == 'course_stackathon' || $template_type == 'course_campaign_page_template'){
          $template_type = 'course_stack_route_ilt';
      }
      if($template_type == 'course_new_landing_page'){
          $template_type = 'course_icici';
      }
    }
    elseif($ContentTypeName == 'course_landing_page'){
      $template_type = $node->field_select_course_landing_type->value; 
    }

    
    $create_application = '';
    if($node->hasField('field_is_application_process')){
      if(!empty($node->get('field_is_application_process')->getValue()[0]['value'])){
        $create_application=$node->get('field_is_application_process')->getValue()[0]['value'];
      }
    }

    $ga_cookie = '';
    if(!empty($_COOKIE['_ga'])){
      $cookie_all = explode('.', $_COOKIE['_ga']);
      $ga_cookie = $cookie_all[2].'.'.$cookie_all[3];
    }

    if($template_type == 'course_icici' || $template_type == 'course_stack_route_ilt' || $template_type == 'course_career' || $template_type == 'course_axis'|| $template_type == 'course_stack_route'){ 
     // if(!empty($create_application) && $create_application == 1){
      // start
      unset($_SESSION['form_step']);

      $campaignCode = $node->get('field_campaign_code')->getValue()[0]['value']; 
      $courseCode = $node->get('field_course_code')->getValue()[0]['value'];
      $CourseType = $node->get('field_delivery_mode_code')->getValue()[0]['value'];

      $url = '';
      if($node->hasField('field_proceed_button_link')){
        if(!empty($node->get('field_proceed_button_link')->getValue()[0]['value'])){
          $url=$node->get('field_proceed_button_link')->getValue()[0]['value'];
        }
      }

      //  $time = time();
      // \Drupal::logger('checked')->notice($time);

      //Login user start
      if(!empty(\Drupal::currentUser()->id())){

        $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
        $currentUserid = $user->id();
        if(!empty($user->get('field_communication_emailid')->value)){
          $userMail = $user->get('field_communication_emailid')->value;
        }
        else{
          $userMail = $user->get('mail')->value;
        }
        $userName = $user->get('field_user_name')->value;
        $userCustomerId = $user->get('field_customer_id')->value;
        $userMobileNo = $user->get('field_mobile_number')->value;    

        // \Drupal::logger('check_loadtime')->notice('Before call application status');
        $finalResult = application_form_status($campaignCode, $courseCode, $currentUserid, 'current_user');
        // \Drupal::logger('check_loadtime')->notice('After call application status');
        if($finalResult['check_eligibility'] == 'Y'){

          if(!empty($create_application) && $create_application == 1){
            $course_id= '';
            $course_batch_id = '';
            $mainCoursedetails = \Drupal::service('niit_common.niit_related_courses')->get_course_fee_and_details($CourseType , $courseCode);
            if(!empty($mainCoursedetails['courseBatchDetail'][0])){
              $course_id = $mainCoursedetails['courseBatchDetail'][0]['courseID'];
              $course_batch_id = $mainCoursedetails['courseBatchDetail'][0]['batchID'];
            }

            $final_json = (array) $finalResult['json_data'];
            $leadusername = $final_json['enqry_f_nm'];
           // $CUSTOMER_ID = $finalResult['CUSTOMER_ID'];
            $update_data = array(
              'source' => 'NIITCOM',
              'CustomerId' => $userCustomerId,
              'RequestedURL'=> '',
              'NewSignup' => 'true',
              'TYPE' => 'U',
              'orgid' => 1,
              'CourseId' => $course_id,
              'BatchId' => $course_batch_id,
              'enqry_crsspndnc_eml' => $userMail,
            );
            $new_json = array_merge($final_json, $update_data);
            $final_json_send = create_application($new_json);

          $continue_btn_form = '';
          $continue_msg = 'You are eligible for the program. Our program advisor will call you shortly.';
          if($finalResult['applctn_opn'] == 'Y'){
            $continue_btn_form = '<form id="" name="form" method="post" action="'.$url.'" class="ContinueYourApplicationForm">
            <input type="hidden" name="eventdata" value="">
            <input type="hidden" name="token" value="'.$final_json_send.'" tabindex="0">
            <input type="submit" value="Continue Your Application" class="btn btn-primary continue-btn">
            </form><div class="hideScript"><script>countiuneYourApplicationEventData();</script></div>';
            $continue_msg = 'You are eligible to apply for the programme.';
          }

            $continue_btn = '<div class="after_login_result check_eligibility_display embed-data">
                              <div class="continue-data">
                               <div class="col-md-12 emb-img">
                                <img src= "/india/themes/custom/nexus/assets/images/confirm-popup.png" class="img-responsive">
                               </div>       
                              <div class="col-md-12 emb-data">
                               <div class="congrats">Congratulations</div>
                                <div class="lead-name">'.$leadusername.'</div>
                                  <div class="lead-des">'.$continue_msg.'</div>
                                  <div class="continue-form">'.$continue_btn_form.'</div>
                              </div>
                            </div>
                            </div>';

            $variables['multistep_page_block_form']=$continue_btn;

            
            $variables['mob_multistep_page_block_form']=$continue_btn;

            // Handle Yes condition

            $variables['mutlistep_apply_btn'] = '<div class="page-embed-form last-signup">'.$continue_btn_form.'</div>';

            $variables['mutlistep_request_call_btn'] = '<div class="page-embed-form req-last-signup">'.$continue_btn_form.'</div>';

            $variables['mutlistep_check_eligibility_btn'] = '<div class="page-embed-form last-signup">'.$continue_btn_form.'</div>';

            $variables['mutlistep_connectus_btn'] = '<div class="page-embed-form connect-last-signup">'.$continue_btn_form.'</div>';

          }
          else{

            $final_json = (array) $finalResult['json_data'];
            $leadusername = $final_json['enqry_f_nm'];

            $continue_btn_form = '';
            $continue_msg = 'You are eligible for the program. Our program advisor will call you shortly.';

            $continue_btn = '<div class="after_login_result check_eligibility_display embed-data">
                              <div class="row continue-data">
                               <div class="col-md-12 emb-img">
                                <img src= "/india/themes/custom/nexus/assets/images/confirm-popup.png" class="img-responsive">
                               </div>       
                              <div class=col-md-12 emb-data">
                               <div class="congrats">Congratulations</div>
                                <div class="lead-name">'.$leadusername.'</div>
                                  <div class="lead-des">'.$continue_msg.'</div>
                                  <div class="continue-form">'.$continue_btn_form.'</div>
                              </div>
                            </div>
                            </div>';

            $variables['multistep_page_block_form']=$continue_btn;

            
            $variables['mob_multistep_page_block_form']=$continue_btn;


            $variables['mutlistep_apply_btn'] = '<span class="btn btnApply grey-btn disabled" title="Our career advisor will connect">Apply Now</span>';

            $variables['mutlistep_request_call_btn'] = '<button class="btn btnReqCall grey-btn disabled" title="Our career advisor will connect"><i class="fa fa-phone"></i> Request a call back</button>';

            $variables['mutlistep_check_eligibility_btn'] = '<span class="btn btnApply grey-btn disabled" title="Our career advisor will connect">Check Eligibility</span>';

            $variables['mutlistep_connectus_btn'] = '<span class="btn btnApply grey-btn disabled" title="Our career advisor will connect">Connect with us</span>';

          }

        }
        elseif($finalResult['check_eligibility'] == 'N'){
           \Drupal::logger('checked1')->notice($time);
          $_SESSION['prev_three_display'] = 1;
          $status_data = [
            'current_step' => 2,
            'finalResult' => $finalResult,
          ];
          $_SESSION['form_step'] = 3;
          $_SESSION['finalResult'] = $finalResult;

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$multistep_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepExampleForm', $status_data, $nid);
				} 
            }

          $variables['multistep_page_block_form'] = $multistep_form;

          
          $variables['mob_multistep_page_block_form'] = $multistep_form;


          $variables['mutlistep_apply_btn'] = '<span class="btn btnApply grey-btn disabled" title="You are not eligible for this program">Apply Now</span>';

          $variables['mutlistep_request_call_btn'] = '<button class="btn btnReqCall grey-btn disabled"  title="You are not eligible for this program"><i class="fa fa-phone"></i> Request a call back</button>';

          $variables['mutlistep_check_eligibility_btn'] = '<span class="btn btnApply grey-btn disabled" title="You are not eligible for this program">Check Eligibility</span>';

          $variables['mutlistep_connectus_btn'] = '<span class="btn btnApply grey-btn disabled" title="You are not eligible for this program">Connect with us</span>';
        }
        else{
          unset($_SESSION['options']);
          $status_data = array();
          if(!empty($finalResult['leadformstg']) && $finalResult['leadformstg'] == '1a'){
            $_SESSION['form_step'] = 2;
            $status_data = [
              'current_step' => 2,
              'finalResult' => $finalResult,
            ];
          }

        $config = \Drupal::config('ms_ajax_form_example.settings');  
        $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
        if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
            $multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
        }else{
			$showSimpleLeadForm = "";
			if($node->hasField('field_show_simple_lead_form')){
				if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
					$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
				}
			}
			if($showSimpleLeadForm == 1){
				$multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
			}else{
				$multistep_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepExampleForm', $status_data, $nid);
			} 
        }
        

          $variables['multistep_page_block_form']=$multistep_form;

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepEmbedPopup', $status_data, $nid);
				} 
            }
          $variables['mob_multistep_page_block_form']=$multistep_form_emded;

          
          $embed_get_in_touch_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepEmbedPopup', $status_data, $nid);
            $get_in_touch_html='
            <div id="ms_ajax_popup_page_embed_Modal" class="modal fade leadLightBox" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                  <div class="modal-body">
                      '.render($embed_get_in_touch_form).'
                  </div>
                </div>
              </div>
            </div>';

          $variables['mob_multistep_page_embed_form']=$embed_get_in_touch_form;

          $variables['multistep_page_embed_form']=$get_in_touch_html;
          $variables['multistep_page_embed_form_btn'] =
              '<span class="cust-btnEnrolNow"><button type="button" 
              class="btn btn-danger career-btnEnrolNow" 
              data-toggle="modal" 
              data-target="#ms_ajax_popup_page_embed_Modal">Get In Touch</button></span>';


            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_popup\Form\MultiStepExampleForm', $status_data, $nid);
				} 
            }
              $enquire_now_html='
              <div id="ms_ajax_popup_page_enquire_Modal" class="modal fade leadLightBox" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                    <div class="modal-body">
                        '.render($enquire_now_form).'
                    </div>
                  </div>
                </div>
              </div>';
            
            $variables['multistep_popup_page_enquire_form']=$enquire_now_html;

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $request_callback_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$request_callback_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$request_callback_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_popup\Form\RequestCallBackForm', $status_data, $nid);
				} 
            }
              $request_call_html='
              <div id="ms_ajax_popup_page_request_callback_Modal" class="modal fade leadLightBox" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                    <div class="modal-body">
                        '.render($request_callback_form).'
                    </div>
                  </div>
                </div>
              </div>';
              
              $variables['multistep_popup_page_callback_form']=$request_call_html;

              $variables['mutlistep_apply_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Apply Now</span>';

              $variables['mutlistep_request_call_btn'] = '<button class="btn btnReqCall" onclick="popupicici_popup()"><i class="fa fa-phone"></i> Request a call back</button>';

              $variables['mutlistep_check_eligibility_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Check Eligibility</span>';

              $variables['mutlistep_connectus_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Connect with us</span>';
        }
      }
        else{
          unset($_SESSION['options']);
            $status_data = array();

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$multistep_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$multistep_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepExampleForm', $status_data, $nid);
				} 
            }
            $variables['multistep_page_block_form']=$multistep_form;

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$multistep_form_emded = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepEmbedPopup', $status_data, $nid);
				} 
            }
            $variables['mob_multistep_page_block_form']=$multistep_form_emded;

            $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $embed_get_in_touch_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$embed_get_in_touch_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$embed_get_in_touch_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_example\Form\MultiStepEmbedPopup', $status_data, $nid);
				} 
            }
              $get_in_touch_html='
              <div id="ms_ajax_popup_page_embed_Modal" class="modal fade leadLightBox" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                    <div class="modal-body">
                        '.render($embed_get_in_touch_form).'
                    </div>
                  </div>
                </div>
              </div>';

            $variables['mob_multistep_page_embed_form']=$embed_get_in_touch_form;

          $variables['multistep_page_embed_form']=$get_in_touch_html;
          $variables['multistep_page_embed_form_btn'] =
                '<span class="cust-btnEnrolNow"><button type="button" 
                class="btn btn-danger career-btnEnrolNow" 
                data-toggle="modal" 
                data-target="#ms_ajax_popup_page_embed_Modal">Get In Touch</button></span>';

           $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$enquire_now_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_popup\Form\MultiStepExampleForm', $status_data, $nid);
				}
            }
            
            $enquire_now_html='
            <div id="ms_ajax_popup_page_enquire_Modal" class="modal fade leadLightBox" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                  <div class="modal-body">
                      '.render($enquire_now_form).'
                  </div>
                </div>
              </div>
            </div>';
          
          $variables['multistep_popup_page_enquire_form']=$enquire_now_html;

          $freeTrialTitle = $node->field_free_trial_cta_title->value;
           $config = \Drupal::config('ms_ajax_form_example.settings');  
            $niit_captureLeadsInCMS = $config->get('CaptureLeadsInCMS');
            if(!empty($niit_captureLeadsInCMS) && $niit_captureLeadsInCMS == 1){ 
                $request_callback_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
            }else{
				$showSimpleLeadForm = "";
				if($node->hasField('field_show_simple_lead_form')){
					if(!empty($node->get('field_show_simple_lead_form')->getValue()[0]['value'])){
						$showSimpleLeadForm = $node->get('field_show_simple_lead_form')->getValue()[0]['value'];
					}
				}
				if($showSimpleLeadForm == 1){
					$request_callback_form = \Drupal::formBuilder()->getForm('Drupal\sso_user\Form\CaptureLeadsInCMSForm', $node->id());
				}else{
					$request_callback_form = \Drupal::formBuilder()->getForm('Drupal\ms_ajax_form_popup\Form\RequestCallBackForm', $status_data, $nid);
				} 
            }
            $request_call_html='
            <div id="ms_ajax_popup_page_request_callback_Modal" class="modal fade leadLightBox" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <button type="button" class="close leadCusCloseBtn" data-dismiss="modal">&times;</button>  
                  <div class="modal-body">
                      '.render($request_callback_form).'
                  </div>
                </div>
              </div>
            </div>';
            
            $variables['multistep_popup_page_callback_form']=$request_call_html;

            $variables['mutlistep_apply_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Apply Now</span>';
            $variables['free_trial_apply_btn'] = '<span class="btn btn-primary btnApply free-trialCTA" onclick="popupicicifree_popup()">'.$freeTrialTitle.' <i class="fa fa-chevron-right"></i></span>';

            $variables['mutlistep_request_call_btn'] = '<button class="btn btnReqCall" onclick="popupicici_popup()"><i class="fa fa-phone"></i> Request a call back</button>';

            $variables['mutlistep_check_eligibility_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Check Eligibility</span>';

            $variables['mutlistep_connectus_btn'] = '<span class="btn btn-primary btnApply" onclick="popupicici_popup()">Connect with us</span>';
        }
        // End
    }
  }*/
}

 function ms_ajax_form_example_js_settings_alter(array &$settings, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

    // Add settings.
    $settings['user']['uid'] = \Drupal::currentUser();
  
    // Manipulate settings.
    if (isset($settings['dialog'])) {
      $settings['dialog']['autoResize'] = FALSE;
    }
  }

function ms_ajax_form_example_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if($form_id == 'camp_ms_form_new_profile_journey_list_form'   || $form_id == 'camp_ms_form_new_profile_journey_list_edit_form'){
    $form['actions']['submit']['#submit'][] = 'new_profile_journey_submit';
  }

}

function new_profile_journey_submit(array $form, FormStateInterface $form_state) {

  $campCodeArray = [];
  $database = \Drupal::database();
  foreach ($form_state->getValue('field_campaign_reference') as $val) {
    if(!empty($val['target_id'])){
      $camp_id = $val['target_id'];
      $check_journey = $database->query("SELECT field_campaign_code_value FROM {camp_ms_form__field_campaign_code}  WHERE  entity_id='$camp_id' and bundle = 'camp_code_master'");
      $campCodeArray[] = $check_journey->fetchfield();
    }
  }

  $intent = 0;
  $eventArray = [];
  foreach ($form_state->getValue('field_event') as $v) {
    if(!empty($v['target_id'])){
      $event_id = $v['target_id'];
      $event_journey = $database->query("SELECT field_event_code_value FROM {camp_ms_form__field_event_code}  WHERE  entity_id='$event_id' and bundle = 'event_master'");
      $eventArray[] = $event_journey->fetchfield();
    }
  }

  $fieldsarray = [];
  foreach($form_state->getValue('field_form_fields') as $value){
    if(!empty($value['field_field_reference'][0]['target_id'])){
      $screen = $value['field_screen_reference'][0]['target_id'];
      $fieldsarray[$screen][] = $value['field_field_reference'][0]['target_id'];
    }
  }

  foreach ($campCodeArray as $campCode) {
    foreach ($eventArray as $event) {
      $screenLevel = 1;
      foreach ($fieldsarray as $k => $value) {

        $a = array(
          'event' => $event,
          'campCode' => $campCode,
          'intent' => $intent,
          'screenLevel' => $screenLevel,
          'field_id' => $value,
          'intent_id' => $k,
        );

        $screenLevel++;

        $batch = array(
          'title' => t('Create fields...'),
          'operations' => array(
            array(
              '\Drupal\ms_ajax_form_example\CreateTableEntry::CallbackApi',
              array($a)
            ),
          ),
          'finished' => '\Drupal\ms_ajax_form_example\CreateTableEntry::CreateTableEntryFinishedCallback',
        );

        batch_set($batch);
 
      }
    }
    
  }
}