block.settings.social_simple_block:
  type: block_settings
  label: 'Social simple block'
  mapping:
    social_share_title:
      type: label
      label: 'Social share title'
    social_networks:
      type: sequence
      label: 'Social networks'
      sequence:
        type: string
        label: 'Social network'

node.type.*.third_party.social_simple:
  type: mapping
  label: 'Per-content type social simple sharing settings'
  mapping:
    share:
      type: integer
      label: 'Enable social simple share links'
    title:
      type: label
      label: 'Social share title'
    networks:
      type: sequence
      label: 'Social networks selected'
      sequence:
       type: string
       label: 'Network machine name'
    hashtags:
      type: string
      label: 'Hashtags source field'